name: Build, Test & Scan

on: push 

jobs:
  build:
    name: All Steps (Build, Test & Scan)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
    
      - name: Install Dependencies
        run: npm ci
          
      - name: Run Unit Tests
        run: npm run test
        
      - name: Build Application
        run: npm run build
